const scene=document.getElementById('scene');
const leftRail=document.getElementById('leftRail');
const rightRail=document.getElementById('rightRail');
const windows=document.getElementById('desktopWindows');
const toastStack=document.getElementById('toastStack');
const vmState=document.getElementById('vmState');
const clock=document.getElementById('clock');
const netState=document.getElementById('netState');

const apps=[
 {id:'lycan-terminal',name:'Terminal',side:'left',icon:'A',meta:'ARES COMMAND'},
 {id:'lycan-files',name:'Files',side:'left',icon:'F',meta:'LYFS FILESPACE'},
 {id:'lycan-web',name:'Web',side:'left',icon:'G',meta:'GECKO BROWSER'},
 {id:'store',name:'Store',side:'left',icon:'S',meta:'PACKAGE ARRAY'},
 {id:'lycan-snapshots',name:'Snapshots',side:'right',icon:'Q',meta:'GUEST STATE'},
 {id:'lycan-diagnostics',name:'Diagnostics',side:'right',icon:'D',meta:'ARES TELEMETRY'},
 {id:'settings',name:'Settings',side:'right',icon:'C',meta:'SYSTEM CONTROL'},
 {id:'crawford',name:'Crawford',side:'right',icon:'K',meta:'AI BOUNDARY'}
];
const open=new Map();let lastEdge='';let z=100;
const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function nodeHTML(a){return `<button class="node" data-app="${a.id}"><span class="node-orb">${a.icon}</span><span class="node-copy"><span class="node-name">${a.name.toUpperCase()}</span><span class="node-meta">${a.meta}</span></span><span class="node-index">${String(apps.indexOf(a)+1).padStart(2,'0')}</span></button>`}
for(const a of apps)(a.side==='left'?leftRail:rightRail).insertAdjacentHTML('beforeend',nodeHTML(a));
function updateClock(){clock.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})} setInterval(updateClock,1000); updateClock();
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;toastStack.appendChild(e);setTimeout(()=>e.remove(),2600)}
async function vm(c){try{return await window.lycan.command(c)}catch(e){throw new Error(e.message||'Backend offline')}}

const defaults={motion:true,compact:false,glow:70,accent:'blue'};
let preferences=(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem('lycan.preferences')||'{}')}}catch{return {...defaults}}})();
function applyPreferences(){document.documentElement.style.setProperty('--blue',preferences.accent==='ice'?'#d4efff':'#79b9ff');document.documentElement.style.setProperty('--blue2',preferences.accent==='ice'?'#effaff':'#b8dcff');document.documentElement.style.setProperty('--glow-strength',String(preferences.glow/100));scene.classList.toggle('reduced-motion',!preferences.motion);scene.classList.toggle('compact-ui',preferences.compact)}
function savePreferences(){localStorage.setItem('lycan.preferences',JSON.stringify(preferences));applyPreferences()}
applyPreferences();

function diagnosticsCards(out){
 const lines=String(out).split('\n').filter(Boolean),data={};
 for(const line of lines){const m=line.match(/^([^=]+?)\s{2,}(\S(?:.*\S)?)$/);if(m)data[m[1].trim()]=m[2].trim()}
 return `<div class="diag-grid"><div class="diag-ring"><div class="diag-ring-inner"><strong>ONLINE</strong><span>ARES CORE</span></div></div><div class="diag-stat"><small>LYFS</small><b>${data.LYFS||'ISOLATED'}</b><span>GUEST STORAGE</span></div><div class="diag-stat"><small>HOST ACCESS</small><b>${data['HOST ACCESS']||'DENIED'}</b><span>BOUNDARY</span></div><div class="diag-stat"><small>NETWORK</small><b>${data.NETWORK||'ONLINE'}</b><span>GUEST LINK</span></div><div class="diag-stat"><small>PROCESSES</small><b>${data.PROCESSES||'—'}</b><span>ARES SCHEDULER</span></div><div class="diag-stat"><small>PACKAGES</small><b>${data.PACKAGES||'—'}</b><span>LYPKG REGISTRY</span></div><div class="diag-stat"><small>FILES</small><b>${data['GUEST FILES']||'—'}</b><span>LYFS OBJECTS</span></div><div class="diag-stat"><small>DATA</small><b>${data['GUEST DATA']||'—'}</b><span>GUEST STORAGE</span></div></div>`;
}
function settingsView(){return `<div class="settings-shell"><div class="settings-head"><div><div class="eyebrow">SYSTEM / INTERFACE CONTROL</div><h2>SETTINGS</h2></div><span>PROFILE // LOCAL</span></div><div class="settings-section"><label>INTERFACE</label><div class="settings-row"><div class="settings-copy"><b>ACCENT PROFILE</b><span>Choose the visual signal used by LYCAN.</span></div><div class="settings-control"><select class="settings-select" data-setting="accent"><option value="blue" ${preferences.accent==='blue'?'selected':''}>LYCAN BLUE</option><option value="ice" ${preferences.accent==='ice'?'selected':''}>ICE WHITE</option></select></div></div><div class="settings-row"><div class="settings-copy"><b>AMBIENT GLOW</b><span>Controls the intensity of core illumination.</span></div><div class="settings-control"><input class="settings-range" type="range" min="0" max="100" value="${preferences.glow}" data-setting="glow"><span class="settings-value" data-glow-value>${preferences.glow}%</span></div></div><div class="settings-row"><div class="settings-copy"><b>REDUCED MOTION</b><span>Disable interface motion and transitions.</span></div><div class="settings-control"><button class="ly-toggle ${!preferences.motion?'on':''}" data-setting="motion"><i></i></button></div></div><div class="settings-row"><div class="settings-copy"><b>COMPACT WINDOWS</b><span>Tighten application surface spacing.</span></div><div class="settings-control"><button class="ly-toggle ${preferences.compact?'on':''}" data-setting="compact"><i></i></button></div></div></div><div class="settings-section"><label>GUEST NETWORK</label><div class="settings-row"><div class="settings-copy"><b>NETWORK LINK</b><span>Guest-only network state. Host network is never exposed.</span></div><div class="settings-control"><button class="ly-toggle ${netState.textContent==='ON'?'on':''}" data-setting="network"><i></i></button></div></div></div><div class="settings-actions"><button data-action="reset-preferences"><b>RESET INTERFACE</b><span>Return LYCAN visual preferences to defaults.</span></button><button data-action="settings-diagnostics"><b>READ SYSTEM STATE</b><span>Refresh guest configuration telemetry.</span></button></div><pre id="settingsOut">PERSISTENT PROFILE ACTIVE\nPreferences stored locally in the LYCAN shell.</pre></div>`}
function crawfordView(){return `<div class="eyebrow">CRAWFORD / CONTROL-PLANE MODULE</div><div class="boundary-shell"><div class="boundary-core"><div class="boundary-line x"></div><div class="boundary-line y"></div><div class="boundary-quad q1"></div><div class="boundary-quad q2"></div><div class="boundary-quad q3"></div><div class="boundary-quad q4"></div><div class="boundary-center"><div><strong>BOUND</strong><span>HOST BRIDGE<br>DENIED</span></div></div></div><div><div class="boundary-list"><div class="boundary-item"><div class="badge">01</div><div><b>MODEL BRIDGE</b><span>External inference connector</span></div><em>OFF</em></div><div class="boundary-item"><div class="badge">02</div><div><b>HOST CONTROL</b><span>Desktop / process control</span></div><em>LOCKED</em></div><div class="boundary-item"><div class="badge">03</div><div><b>GUEST CONTEXT</b><span>LYFS + ARES telemetry</span></div><em>READ</em></div><div class="boundary-item"><div class="badge">04</div><div><b>NETWORK</b><span>Guest network channel</span></div><em>${netState.textContent}</em></div></div><div class="crawford-actions"><button data-action="crawford-audit"><b>AUDIT BOUNDARY</b><span>Verify current isolation posture.</span></button><button data-action="crawford-runtime"><b>INSPECT RUNTIME</b><span>Read ARES and process state.</span></button></div><pre class="audit-log" id="crawfordLog">CRAWFORD CONTROL PLANE READY\nNo host-control capability granted.\nAwaiting explicit inspection command.</pre></div></div>`}

const surfaces={
 'lycan-terminal':{title:'TERMINAL',tag:'ARES',render:o=>`<div class="eyebrow">ARES / COMMAND PROCESSOR</div><div class="command-row"><input id="term" autocomplete="off" placeholder="enter command"><button data-action="terminal">RUN</button></div><pre id="termOut">${esc(o)}</pre>`},
 'lycan-files':{title:'FILES',tag:'LYFS',render:o=>`<div class="eyebrow">LYFS / GUEST FILESYSTEM</div><div class="status-cards"><div class="status-card"><small>VOLUME</small><strong>LYFS</strong></div><div class="status-card"><small>ROOT</small><strong>/home</strong></div><div class="status-card"><small>MODE</small><strong>GUEST RW</strong></div><div class="status-card"><small>HOST</small><strong>BLOCKED</strong></div></div><div class="command-row"><input id="path" value="/home" autocomplete="off"><button data-action="files">INSPECT</button></div><pre id="fileOut">${esc(o)}</pre>`},
 'lycan-web':{title:'WEB',tag:'GECKO',render:o=>`<div class="eyebrow">GECKO / NATIVE BROWSER PROCESS</div><div class="command-row"><input id="url" autocomplete="off" placeholder="https://example.com"><button data-action="web">LAUNCH GECKO</button></div><pre>${esc(o)}</pre><div class="runtime-chip">ENGINE <span>GECKO</span><br>ISOLATION <span>DEDICATED PROFILE</span></div>`},
 'store':{title:'STORE',tag:'LYPKG',render:o=>`<div class="eyebrow">LYPKG / APPLICATION ARRAY</div><div class="status-cards"><div class="status-card"><small>CATALOG</small><strong>FREE</strong></div><div class="status-card"><small>FORMAT</small><strong>.LYPKG</strong></div><div class="status-card"><small>VERIFY</small><strong>SHA-256</strong></div><div class="status-card"><small>INSTALL</small><strong>ATOMIC</strong></div></div><div class="command-row"><button data-action="install" style="min-height:42px">INSTALL .LYPKG</button><button data-action="refresh-store" style="min-height:42px">REFRESH ARRAY</button></div><pre>${esc(o)}</pre>`},
 'lycan-snapshots':{title:'SNAPSHOTS',tag:'STATE',render:o=>`<div class="eyebrow">GUEST STATE / CHECKPOINTS</div><div class="snapshot-console"><div class="snapshot-create"><div class="snapshot-mark"><span>Q</span><small>ARES STATE</small></div><input id="snap" autocomplete="off" placeholder="checkpoint name"><button data-action="snapshot">CREATE CHECKPOINT</button></div><div class="snapshot-toolbar"><span>LOCAL GUEST CHECKPOINTS</span><button data-action="snapshots">SCAN</button></div><pre id="snapOut">${esc(o)}</pre><div class="snapshot-actions"><button data-action="restore"><b>RESTORE</b><span>Rehydrate selected checkpoint state</span></button><button data-action="info"><b>INSPECT</b><span>Read serialized checkpoint metadata</span></button><button data-action="delete-snapshot"><b>DELETE</b><span>Remove a guest checkpoint</span></button></div></div>`},
 'lycan-diagnostics':{title:'DIAGNOSTICS',tag:'ARES',render:o=>`<div class="eyebrow">ARES / SYSTEM TELEMETRY</div>${diagnosticsCards(o)}<div class="telemetry-bar"><span>RUNTIME INTEGRITY</span><i></i><b>ENFORCED</b></div><pre>${esc(o)}</pre>`},
 'settings':{title:'SETTINGS',tag:'CONTROL',render:()=>settingsView()},
 'crawford':{title:'CRAWFORD',tag:'BOUNDARY',render:()=>crawfordView()}
};
function focus(win){win.style.zIndex=++z;document.querySelectorAll('.app-window.is-focused').forEach(w=>w.classList.remove('is-focused'));win.classList.add('is-focused')}
async function openApp(id){if(open.has(id)){focus(open.get(id));return}const meta=surfaces[id];if(!meta)return;const win=document.createElement('article');win.className='app-window';win.style.zIndex=++z;win.innerHTML=`<div class="window-bar"><div class="window-title"><span class="window-dot"></span>${meta.title}<span class="window-tag">${meta.tag}</span></div><button class="window-close" aria-label="Close">×</button></div><div class="window-body"><div class="hero"><div><div class="eyebrow">LYCAN RUNTIME</div><h2>INITIALIZING</h2><p>ATTACHING TO GUEST PROCESS</p></div></div></div>`;windows.appendChild(win);open.set(id,win);focus(win);try{const command=id==='store'?'apps':id==='settings'?'version':id==='crawford'?'version':id==='lycan-files'?'ls /home':id==='lycan-web'?'web start':id==='lycan-snapshots'?'snapshots':id==='lycan-diagnostics'?'diagnostics':'help';const out=await vm(command);win.querySelector('.window-body').innerHTML=meta.render(out);focus(win);toast(`${meta.title} ONLINE`)}catch(e){win.querySelector('.window-body').innerHTML=`<div class="hero"><div><div class="eyebrow">RUNTIME FAULT</div><h2>BACKEND ERROR</h2><p>${esc(e.message)}</p></div></div>`;toast(e.message)}win.addEventListener('mousedown',()=>focus(win));win.addEventListener('change',e=>handleSettingChange(e,id));win.addEventListener('input',e=>handleSettingChange(e,id));win.addEventListener('click',e=>{if(e.target.closest('.window-close')){win.classList.add('closing');setTimeout(()=>{win.remove();open.delete(id)},180);return}const action=e.target.closest('[data-action]')?.dataset.action;if(action)runAction(id,action)})}
window.openApp=openApp;
function handleSettingChange(e,id){if(id!=='settings')return;const key=e.target?.dataset?.setting;if(!key)return;if(key==='accent'){preferences.accent=e.target.value;savePreferences();toast('ACCENT PROFILE UPDATED')}if(key==='glow'){preferences.glow=Number(e.target.value)||0;savePreferences();const v=e.target.closest('.settings-control')?.querySelector('[data-glow-value]');if(v)v.textContent=`${preferences.glow}%`;}if(key==='motion'){preferences.motion=!preferences.motion;savePreferences();e.target.classList.toggle('on',!preferences.motion);toast(preferences.motion?'MOTION ENABLED':'MOTION REDUCED')}if(key==='compact'){preferences.compact=!preferences.compact;savePreferences();e.target.classList.toggle('on',preferences.compact);toast(preferences.compact?'COMPACT MODE ON':'COMPACT MODE OFF')}if(key==='network'){const next=netState.textContent!=='ON';vm(next?'network on':'network off').then(()=>{netState.textContent=next?'ON':'OFF';e.target.classList.toggle('on',next);toast(`NETWORK ${next?'ONLINE':'OFFLINE'}`)}).catch(err=>toast(err.message))}}
async function runAction(id,a){try{const win=open.get(id);let out='';if(a==='terminal'){const v=win?.querySelector('#term')?.value.trim();if(!v)return;out=await vm(v);win.querySelector('#termOut').textContent=out;win.querySelector('#term').value='';return}if(a==='files'){const v=win?.querySelector('#path')?.value.trim()||'/home';win.querySelector('#fileOut').textContent=await vm(`ls ${v}`);return}if(a==='web'){const v=win?.querySelector('#url')?.value.trim()||'about:blank';const r=await window.lycan.gecko(v);out=r.ok?`GECKO PROCESS STARTED\n${r.executable}\nPROFILE\n${r.profile}`:`GECKO LAUNCH FAILED\n${r.error}`;win.querySelector('pre').textContent=out;toast(r.ok?'GECKO ENGINE STARTED':'GECKO NOT AVAILABLE');return}if(a==='install'){const r=await window.lycan.installPackage();if(r?.canceled)return;out=r?.ok?`INSTALLED\n${r.name}\nID ${r.id}\nVERSION ${r.version}`:`INSTALL FAILED\n${r?.error||'Unknown error'}`;const pre=win.querySelector('pre');if(pre)pre.textContent=out;toast(r?.ok?'LYPKG INSTALLED':'LYPKG INSTALL FAILED');return}if(a==='refresh-store'||a==='apps')out=await vm('apps');if(a==='snapshot'){const v=win?.querySelector('#snap')?.value.trim()||'manual';out=await vm(`snapshot ${v}`);win.querySelector('#snapOut').textContent=out;win.querySelector('#snap').value='';return}if(a==='snapshots')out=await vm('snapshots');if(a==='restore'){const v=win?.querySelector('#snap')?.value.trim();if(!v)return toast('ENTER CHECKPOINT NAME');out=await vm(`restore ${v}`)}if(a==='info'){const v=win?.querySelector('#snap')?.value.trim();if(!v)return toast('ENTER CHECKPOINT NAME');out=await vm(`snapshot-info ${v}`)}if(a==='delete-snapshot'){const v=win?.querySelector('#snap')?.value.trim();if(!v)return toast('ENTER CHECKPOINT NAME');out=await vm(`delete-snapshot ${v}`)}if(a==='reset-preferences'){preferences={...defaults};savePreferences();win.querySelector('.window-body').innerHTML=surfaces.settings.render('');toast('INTERFACE RESET');return}if(a==='settings-diagnostics'){out=await vm('diagnostics')}if(a==='crawford-audit'){const lines=['CRAWFORD BOUNDARY AUDIT','HOST BRIDGE       DENIED','NODE ACCESS       GUEST ONLY','LYFS             ISOLATED','PROCESS CONTROL  RESTRICTED','NETWORK          GUEST LINK','RESULT           PASS'];win.querySelector('#crawfordLog').textContent=lines.join('\n');toast('BOUNDARY AUDIT PASSED');return}if(a==='crawford-runtime'){out=await vm('ps');win.querySelector('#crawfordLog').textContent=`ARES RUNTIME\n${out}`;toast('RUNTIME INSPECTED');return}const pre=win?.querySelector('#settingsOut')||win?.querySelector('pre');if(pre&&out)pre.textContent=out;toast(out.split('\n')[0]||'DONE');if(a==='restore'){await refreshNetwork();toast('GUEST STATE RESTORED')}}catch(e){toast(e.message)}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-app]')?.dataset.app;if(a)openApp(a);if(e.target.id==='logo')scene.classList.toggle('node-open')});
document.addEventListener('mousemove',e=>{const threshold=70;const edge=e.clientX<threshold?'left':e.clientX>innerWidth-threshold?'right':'';if(edge!==lastEdge){lastEdge=edge;scene.classList.toggle('edge-left',edge==='left');scene.classList.toggle('edge-right',edge==='right')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(document.querySelector('.launcher-shell.visible'))return;for(const [id,w] of open){w.classList.add('closing');setTimeout(()=>w.remove(),140)}open.clear();scene.classList.remove('node-open')}if(e.key===' '&&!e.target.matches('input,textarea'))scene.classList.toggle('node-open')});
async function refreshNetwork(){try{const status=await vm('network');netState.textContent=status.endsWith('ONLINE')?'ON':'OFF'}catch(_){netState.textContent='--'}}
async function bootHandshake(){vmState.textContent='BOOTING';scene.classList.add('vm-booting');try{await new Promise(r=>setTimeout(r,300));const pong=await vm('ping');if(pong!=='LYCAN VM ONLINE')throw new Error('Unexpected VM response');await new Promise(r=>setTimeout(r,320));vmState.textContent='ONLINE';scene.classList.remove('vm-booting');await refreshNetwork();toast('ARES / GUEST ENVIRONMENT READY')}catch(e){vmState.textContent='OFFLINE';scene.classList.remove('vm-booting');toast(`VM CONNECTION FAILED: ${e.message}`)}}
setInterval(refreshNetwork,5000);bootHandshake();