const scene=document.getElementById('scene');const leftRail=document.getElementById('leftRail');const rightRail=document.getElementById('rightRail');const windows=document.getElementById('desktopWindows');const toastStack=document.getElementById('toastStack');const vmState=document.getElementById('vmState');const clock=document.getElementById('clock');
const apps=[
 {id:'lycan-terminal',name:'Terminal',side:'left',icon:'>_',meta:'ARES COMMAND'},
 {id:'lycan-files',name:'Files',side:'left',icon:'⌁',meta:'LYFS FILESPACE'},
 {id:'lycan-web',name:'Web',side:'left',icon:'◎',meta:'GECKO BROWSER'},
 {id:'store',name:'Store',side:'left',icon:'◫',meta:'FREE APPLICATIONS'},
 {id:'lycan-snapshots',name:'Snapshots',side:'right',icon:'◒',meta:'GUEST STATE'},
 {id:'lycan-diagnostics',name:'Diagnostics',side:'right',icon:'◈',meta:'ARES TELEMETRY'},
 {id:'settings',name:'Settings',side:'right',icon:'⚙',meta:'SYSTEM CONTROL'},
 {id:'crawford',name:'Crawford',side:'right',icon:'✦',meta:'AI BOUNDARY'}
];
const open=new Map();let lastEdge='';let z=10;
function nodeHTML(a){return `<button class="node" data-app="${a.id}"><span class="node-orb">${a.icon}</span><span class="node-copy"><span class="node-name">${a.name.toUpperCase()}</span><span class="node-meta">${a.meta}</span></span></button>`}
for(const a of apps)(a.side==='left'?leftRail:rightRail).insertAdjacentHTML('beforeend',nodeHTML(a));
function updateClock(){clock.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}).toUpperCase()}setInterval(updateClock,1000);updateClock();
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;toastStack.appendChild(e);setTimeout(()=>e.remove(),2600)}
async function vm(c){try{return await window.lycan.command(c)}catch(e){throw new Error(e.message||'Backend offline')}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const surfaces={
 'lycan-terminal':{title:'TERMINAL',tag:'ARES',render:o=>`<div class="command-row"><input id="term" placeholder="Enter ARES command…"><button data-action="terminal">EXECUTE</button></div><pre id="termOut">${esc(o)}</pre>`},
 'lycan-files':{title:'FILES',tag:'LYFS',render:o=>`<div class="status-cards"><div class="status-card"><small>FILESYSTEM</small><strong>LYFS</strong></div><div class="status-card"><small>PATH</small><strong>/home</strong></div><div class="status-card"><small>ACCESS</small><strong>RW</strong></div><div class="status-card"><small>SPACE</small><strong>VIRTUAL</strong></div></div><div class="command-row"><input id="path" value="/home"><button data-action="files">OPEN</button></div><pre id="fileOut">${esc(o)}</pre>`},
 'lycan-web':{title:'WEB',tag:'GECKO',render:o=>`<div class="command-row"><input id="url" placeholder="https://example.com"><button data-action="web">NAVIGATE</button></div><pre>${esc(o)}</pre><div style="margin-top:18px;color:#66738c;font-size:8px;letter-spacing:.13em">GECKO RUNTIME BOUNDARY • NO WEBVIEW2 FALLBACK</div>`},
 'store':{title:'STORE',tag:'FREE',render:o=>`<div class="status-cards"><div class="status-card"><small>ECONOMY</small><strong>FREE</strong></div><div class="status-card"><small>VERIFICATION</small><strong>SHA-256</strong></div><div class="status-card"><small>INSTALL</small><strong>ATOMIC</strong></div><div class="status-card"><small>STATE</small><strong>LIVE</strong></div></div><pre>${esc(o)}</pre><div class="quick-grid"><button class="quick" data-action="apps"><b>INSTALLED APPS</b><span>Read the package database.</span></button><button class="quick" data-action="launcher"><b>LAUNCHER REGISTRY</b><span>Read registered applications.</span></button></div>`},
 'lycan-snapshots':{title:'SNAPSHOTS',tag:'STATE',render:o=>`<div class="command-row"><input id="snap" placeholder="snapshot name"><button data-action="snapshot">SAVE</button></div><pre id="snapOut">${esc(o)}</pre><div class="quick-grid"><button class="quick" data-action="snapshots"><b>REFRESH</b><span>Read snapshots.</span></button><button class="quick" data-action="snapshot-manual"><b>QUICK SAVE</b><span>Save current guest metadata.</span></button></div>`},
 'lycan-diagnostics':{title:'DIAGNOSTICS',tag:'ARES',render:o=>`<div class="status-cards"><div class="status-card"><small>ARES</small><strong>ONLINE</strong></div><div class="status-card"><small>LYFS</small><strong>ONLINE</strong></div><div class="status-card"><small>SECURITY</small><strong>ENFORCED</strong></div><div class="status-card"><small>VM</small><strong>ACTIVE</strong></div></div><pre>${esc(o)}</pre>`},
 'settings':{title:'SETTINGS',tag:'SYSTEM',render:o=>`<div class="status-cards"><div class="status-card"><small>CPU</small><strong>2 CORES</strong></div><div class="status-card"><small>MEMORY</small><strong>512 MB</strong></div><div class="status-card"><small>NETWORK</small><strong>ENABLED</strong></div><div class="status-card"><small>PACKAGES</small><strong>STRICT</strong></div></div><pre>${esc(o)}</pre>`},
 'crawford':{title:'CRAWFORD',tag:'AI',render:o=>`<div class="hero"><div><h2>CRAWFORD</h2><p>AI integration boundary • host bridge denied by default</p><pre>${esc(o)}</pre></div></div>`}
};
async function openApp(id){if(open.has(id)){open.get(id).style.zIndex=++z;return}const meta=surfaces[id];if(!meta)return;const win=document.createElement('article');win.className='app-window';win.style.zIndex=++z;win.innerHTML=`<div class="window-bar"><div class="window-title"><span class="window-dot"></span>${meta.title}<span style="color:#56617a;font-size:8px;letter-spacing:.12em">${meta.tag}</span></div><button class="window-close">×</button></div><div class="window-body"><div class="hero"><div><h2>CONNECTING</h2><p>ESTABLISHING LYCAN SESSION</p></div></div></div>`;windows.appendChild(win);open.set(id,win);win.addEventListener('mousedown',()=>win.style.zIndex=++z);try{const command=id==='store'?'launcher':id==='settings'?'settings':id==='crawford'?'runtime':id==='lycan-files'?'ls /home':id==='lycan-web'?'web start':id==='lycan-snapshots'?'snapshots':id==='lycan-diagnostics'?'diagnostics':'help';const out=await vm(command);win.querySelector('.window-body').innerHTML=meta.render(out);toast(`${meta.title} opened`)}catch(e){win.querySelector('.window-body').innerHTML=`<div class="hero"><div><h2>BACKEND ERROR</h2><p>${esc(e.message)}</p></div></div>`;toast(e.message)}win.addEventListener('click',e=>{if(e.target.closest('.window-close')){win.remove();open.delete(id);return}const action=e.target.closest('[data-action]')?.dataset.action;if(action)runAction(id,action)})}
async function runAction(id,a){try{let out='';if(a==='terminal'){const v=document.getElementById('term').value.trim();if(!v)return;out=await vm(v);document.getElementById('termOut').textContent=out;document.getElementById('term').value='';return}if(a==='files'){const v=document.getElementById('path').value.trim()||'/home';document.getElementById('fileOut').textContent=await vm(`ls ${v}`);return}if(a==='web'){const v=document.getElementById('url').value.trim();if(v)out=await vm(`web tab ${v}`)}if(a==='snapshot'){const v=document.getElementById('snap').value.trim()||'manual';out=await vm(`snapshot ${v}`);document.getElementById('snapOut').textContent=out;return}if(a==='snapshot-manual'||a==='snapshots')out=await vm(a==='snapshots'?'snapshots':'snapshot manual');if(a==='apps')out=await vm('apps');if(a==='launcher')out=await vm('launcher');const body=open.get(id)?.querySelector('.window-body');const pre=body?.querySelector('pre');if(pre&&out)pre.textContent=out;toast(out.split('\n')[0]||'DONE')}catch(e){toast(e.message)}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-app]')?.dataset.app;if(a)openApp(a);if(e.target.id==='logo')scene.classList.toggle('node-open')});
document.addEventListener('mousemove',e=>{const threshold=76;const edge=e.clientX<threshold?'left':e.clientX>innerWidth-threshold?'right':'';if(edge!==lastEdge){lastEdge=edge;scene.classList.toggle('edge-left',edge==='left');scene.classList.toggle('edge-right',edge==='right')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){for(const [id,w] of open){w.remove()}open.clear();scene.classList.remove('node-open')}if(e.key===' '&&!e.target.matches('input'))scene.classList.toggle('node-open')});
vmState.textContent='ONLINE';toast('ARES virtual environment online');
