#include "app_runtime.h"
#include <algorithm>
namespace lycan {
const char* appStateName(AppState s) noexcept { switch(s){case AppState::Created:return "created";case AppState::Starting:return "starting";case AppState::Running:return "running";case AppState::Suspended:return "suspended";case AppState::Crashed:return "crashed";default:return "stopped";} }
bool IpcBus::send(const IpcMessage& m){ if(m.sender.empty()||m.receiver.empty()||m.topic.empty()) return false; queue_.push_back(m); return true; }
bool IpcBus::receive(const std::string& r,IpcMessage& out){auto it=std::find_if(queue_.begin(),queue_.end(),[&](const auto&m){return m.receiver==r;});if(it==queue_.end())return false;out=*it;queue_.erase(it);return true;}
std::vector<IpcMessage> IpcBus::pending(const std::string& r)const{std::vector<IpcMessage>v;for(const auto&m:queue_)if(m.receiver==r)v.push_back(m);return v;}
size_t IpcBus::size()const noexcept{return queue_.size();}
AppRuntime::AppRuntime(Lyfs&f,ProcessManager&p,SecurityPolicy&s,PackageManager&pm):fs_(f),processes_(p),security_(s),packages_(pm){}
bool AppRuntime::safeRelativePath(const std::string&p){if(p.empty()||p[0]=='/'||p.find('\\')!=std::string::npos)return false;size_t pos=0;while((pos=p.find("..",pos))!=std::string::npos){bool left=(pos==0||p[pos-1]=='/');bool right=(pos+2==p.size()||p[pos+2]=='/');if(left&&right)return false;pos+=2;}return true;}
std::string AppRuntime::sandboxPath(const std::string&id,const std::string&rel)const{return "/home/.apps/"+id+"/data/"+rel;}
bool AppRuntime::hasPermission(const AppRuntimeInfo&a,Capability c)const{const char*n=nullptr;switch(c){case Capability::ReadGuestFs:n="lyfs.read";break;case Capability::WriteGuestFs:n="lyfs.write";break;case Capability::Network:n="network";break;case Capability::LaunchProcess:n="process.launch";break;case Capability::HostBridge:n="host.bridge";break;}return std::find(a.permissions.begin(),a.permissions.end(),n)!=a.permissions.end();}
bool AppRuntime::installEnvironment(const Package&p,AppRuntimeInfo*out,std::string*e){if(p.id.empty()){if(e)*e="invalid package id";return false;}auto& a=apps_[p.id];a.id=p.id;a.version=p.version;a.permissions=p.permissions;a.sandboxRoot="/home/.apps/"+p.id;a.environment.variables={{"LYCAN_APP_ID",p.id},{"LYCAN_APP_VERSION",p.version},{"LYCAN_SANDBOX",a.sandboxRoot}};a.limits.memoryKiB=64*1024;a.state=AppState::Created;if(!fs_.createDirectory("/home/.apps")){}if(!fs_.createDirectory(a.sandboxRoot)){}if(!fs_.createDirectory(a.sandboxRoot+"/data")){}if(out)*out=a;return true;}
bool AppRuntime::requestCapability(const std::string&id,Capability c,std::string*e){auto it=apps_.find(id);if(it==apps_.end()){if(e)*e="application not registered";return false;}if(!security_.allowed(c)){if(e)*e="capability globally denied";return false;}if(!hasPermission(it->second,c)){if(e)*e="capability not granted by package";return false;}return true;}
bool AppRuntime::start(const std::string&id,std::string*e){auto it=apps_.find(id);if(it==apps_.end()){if(e)*e="application not registered";return false;}if(const auto* p=processes_.findApp(id)){it->second.pid=p->pid;it->second.state=AppState::Running;return true;}it->second.state=AppState::Starting;auto pid=processes_.launchApp(id,"package://"+id,it->second.limits.memoryKiB);if(!pid){it->second.state=AppState::Crashed;if(e)*e="process launch failed";return false;}it->second.pid=pid;it->second.state=AppState::Running;return true;}
bool AppRuntime::suspend(const std::string&id){auto it=apps_.find(id);return it!=apps_.end()&&it->second.pid&&processes_.suspend(it->second.pid)?(it->second.state=AppState::Suspended,true):false;}
bool AppRuntime::resume(const std::string&id){auto it=apps_.find(id);return it!=apps_.end()&&it->second.pid&&processes_.resume(it->second.pid)?(it->second.state=AppState::Running,true):false;}
bool AppRuntime::stop(const std::string&id){auto it=apps_.find(id);if(it==apps_.end())return false;bool ok=it->second.pid?processes_.stop(it->second.pid):true;it->second.pid=0;it->second.state=AppState::Stopped;return ok;}
bool AppRuntime::crash(const std::string&id,std::string reason,std::string detail){auto it=apps_.find(id);if(it==apps_.end())return false;if(it->second.pid)processes_.stop(it->second.pid);it->second.pid=0;it->second.state=AppState::Crashed;it->second.crashes.push_back({crashSequence_++,std::move(reason),std::move(detail)});return true;}
bool AppRuntime::sendIpc(const std::string&s,const std::string&r,const std::string&t,const std::string&p,std::string*e){auto si=apps_.find(s),ri=apps_.find(r);if(si==apps_.end()||ri==apps_.end()){if(e)*e="unknown application";return false;}if(!hasPermission(si->second,Capability::HostBridge)&&s!=r){if(e)*e="IPC capability not granted";return false;}if(ipc_.pending(r).size()>=si->second.limits.maxIpcMessages){if(e)*e="IPC quota exceeded";return false;}return ipc_.send({s,r,t,p});}
bool AppRuntime::receiveIpc(const std::string&r,IpcMessage&o){return ipc_.receive(r,o);}
bool AppRuntime::writeSandboxFile(const std::string&id,const std::string&rel,const std::string&text,std::string*e){auto it=apps_.find(id);if(it==apps_.end()||!hasPermission(it->second,Capability::WriteGuestFs)){if(e)*e="filesystem write capability denied";return false;}if(!safeRelativePath(rel)){if(e)*e="unsafe sandbox path";return false;}return fs_.writeText(sandboxPath(id,rel),text)||(e?(*e="write failed",false):false);}
bool AppRuntime::readSandboxFile(const std::string&id,const std::string&rel,std::string&text,std::string*e)const{auto it=apps_.find(id);if(it==apps_.end()||!hasPermission(it->second,Capability::ReadGuestFs)){if(e)*e="filesystem read capability denied";return false;}if(!safeRelativePath(rel)){if(e)*e="unsafe sandbox path";return false;}return fs_.readText(sandboxPath(id,rel),text)||(e?(*e="read failed",false):false);}
const AppRuntimeInfo* AppRuntime::find(const std::string&id)const noexcept{auto it=apps_.find(id);return it==apps_.end()?nullptr:&it->second;}
std::vector<AppRuntimeInfo> AppRuntime::list()const{std::vector<AppRuntimeInfo>v;for(const auto&[id,a]:apps_)v.push_back(a);return v;}
const IpcBus& AppRuntime::ipc()const noexcept{return ipc_;}
} // namespace lycan
