#include "package_manager.h"
#include "package_archive.h"
#include <cctype>
#include <fstream>
namespace lycan {
PackageManager::PackageManager(Lyfs&fs,SecurityPolicy&s):fs_(fs),security_(s),db_(fs_.hostPath("/system/packages.db")){}
bool PackageManager::validId(const std::string&id){if(id.empty()||id.size()>80)return false;for(unsigned char c:id)if(!(std::isalnum(c)||c=='-'||c=='_'||c=='.'))return false;return true;}
bool PackageManager::install(const Package&p){if(!validId(p.id)||p.publisher.empty()||!security_.publisherTrusted(p.publisher)||!fs_.createDirectory("/apps/"+p.id))return false;std::string m="{\n  \"id\": \""+p.id+"\",\n  \"name\": \""+p.name+"\",\n  \"version\": \""+p.version+"\",\n  \"publisher\": \""+p.publisher+"\",\n  \"entry\": \""+p.entry+"\"\n}\n";if(!fs_.writeText("/apps/"+p.id+"/manifest.json",m))return false;std::ofstream db(db_,std::ios::app);return(bool)db&&(db<<p.id<<"|"<<p.version<<"|"<<p.publisher<<"\n");}
bool PackageManager::inspectArchive(const std::filesystem::path&path,Package&pkg,std::string*error)const{PackageManifest m;std::vector<PackageEntry>entries;std::string e;if(!PackageArchive::inspect(path,m,entries,e)){if(error)*error=e;return false;}pkg.id=m.id;pkg.name=m.name;pkg.version=m.version;pkg.publisher=m.publisher;pkg.entry=m.entry;pkg.permissions=m.permissions;pkg.source=path;if(!validId(pkg.id)){if(error)*error="invalid package id";return false;}if(pkg.entry.rfind("/apps/"+pkg.id+"/",0)!=0){if(error)*error="manifest entry must stay inside its app";return false;}return true;}
bool PackageManager::installArchive(const std::filesystem::path&path,std::string*error){Package p;std::string e;if(!inspectArchive(path,p,&e)){if(error)*error=e;return false;}if(!security_.publisherTrusted(p.publisher)){if(error)*error="publisher is not trusted";return false;}auto target=fs_.hostPath("/apps/"+p.id);std::error_code ec;std::filesystem::create_directories(target,ec);if(ec){if(error)*error=ec.message();return false;}PackageManifest manifest;std::vector<PackageEntry>entries;if(!PackageArchive::inspect(path,manifest,entries,e)||!PackageArchive::extract(path,target,manifest,e)){if(error)*error=e;return false;}std::ofstream db(db_,std::ios::app);if(!db||(db<<p.id<<"|"<<p.version<<"|"<<p.publisher<<"\n").fail()){if(error)*error="cannot update package database";return false;}return true;}
bool PackageManager::uninstall(const std::string&id){return validId(id)&&fs_.remove("/apps/"+id);}
bool PackageManager::rollback(const std::string&id){return validId(id)&&fs_.ready();}
std::vector<Package> PackageManager::installed()const{std::vector<Package>v;for(auto&e:fs_.list("/apps"))if(e.directory){Package p;p.id=e.path.substr(6);p.name=p.id;p.version="1.0.0";p.publisher="LYCAN";std::string j;if(fs_.readText("/apps/"+p.id+"/manifest.json",j)){auto value=[&](const std::string&k){auto n="\""+k+"\"";auto a=j.find(n);if(a==std::string::npos)return std::string{};a=j.find(':',a+n.size());auto q=j.find('"',a);auto z=j.find('"',q+1);return q==std::string::npos||z==std::string::npos?std::string{}:j.substr(q+1,z-q-1);};auto x=value("name");if(!x.empty())p.name=x;x=value("version");if(!x.empty())p.version=x;x=value("publisher");if(!x.empty())p.publisher=x;x=value("entry");if(!x.empty())p.entry=x;}v.push_back(p);}return v;}
}
