#include "lycan_platform.h"
#include <algorithm>
#include <sstream>
namespace lycan {
Memory::Memory(size_t n):b_(n,0){} size_t Memory::size()const{return b_.size();}
bool Memory::read8(uint64_t a,uint8_t&v)const{if(a>=b_.size()||!canRead(a))return false;v=b_[a];return true;} bool Memory::write8(uint64_t a,uint8_t v){if(a>=b_.size()||!canWrite(a))return false;b_[a]=v;return true;}
bool Memory::read64(uint64_t a,uint64_t&v)const{if(a+8>b_.size())return false;v=0;for(int i=0;i<8;i++){uint8_t x;if(!read8(a+i,x))return false;v|=(uint64_t)x<<(i*8);}return true;} bool Memory::write64(uint64_t a,uint64_t v){if(a+8>b_.size())return false;for(int i=0;i<8;i++)if(!write8(a+i,(uint8_t)(v>>(i*8))))return false;return true;}
bool Memory::map(uint64_t a,uint64_t n,bool r,bool w,bool x){if(!n||a+n>b_.size())return false;regions_.push_back({a,n,r,w,x});return true;} bool Memory::canRead(uint64_t a)const{for(auto i=regions_.rbegin();i!=regions_.rend();++i)if(a>=i->a&&a<i->a+i->n)return i->r;return regions_.empty();} bool Memory::canWrite(uint64_t a)const{for(auto i=regions_.rbegin();i!=regions_.rend();++i)if(a>=i->a&&a<i->a+i->n)return i->w;return regions_.empty();} bool Memory::canExecute(uint64_t a)const{for(auto i=regions_.rbegin();i!=regions_.rend();++i)if(a>=i->a&&a<i->a+i->n)return i->x;return regions_.empty();}
CPU::CPU(Memory&m):m_(m){} void CPU::reset(uint64_t e,uint64_t st){s_={};s_.pc=e;s_.sp=st;} void CPU::z(uint64_t x){if(x)s_.flags&=~1ull;else s_.flags|=1ull;} bool CPU::fetch8(uint8_t&v){if(!m_.canExecute(s_.pc)||!m_.read8(s_.pc,v))return false;s_.pc++;return true;} bool CPU::fetch64(uint64_t&v){if(!m_.canExecute(s_.pc))return false;if(!m_.read64(s_.pc,v))return false;s_.pc+=8;return true;}
bool CPU::step(){if(s_.halted)return false;uint8_t o,a,b;uint64_t x;if(!fetch8(o)){s_.halted=true;return false;}switch((Op)o){case Op::NOP:break;case Op::MOV:if(!fetch8(a)||!fetch64(x)||a>7){s_.halted=true;return false;}s_.r[a]=x;z(x);break;case Op::ADD:case Op::SUB:case Op::MUL:case Op::DIV:if(!fetch8(a)||!fetch8(b)||a>7||b>7||(o==(uint8_t)Op::DIV&&!s_.r[b])){s_.halted=true;s_.flags|=2;return false;}if(o==(uint8_t)Op::ADD)s_.r[a]+=s_.r[b];else if(o==(uint8_t)Op::SUB)s_.r[a]-=s_.r[b];else if(o==(uint8_t)Op::MUL)s_.r[a]*=s_.r[b];else s_.r[a]/=s_.r[b];z(s_.r[a]);break;case Op::CMP:if(!fetch8(a)||!fetch8(b)||a>7||b>7){s_.halted=true;return false;}z(s_.r[a]-s_.r[b]);break;case Op::JMP:if(!fetch64(x)){s_.halted=true;return false;}s_.pc=x;break;case Op::JZ:if(!fetch64(x)){s_.halted=true;return false;}if(s_.flags&1)s_.pc=x;break;case Op::JNZ:if(!fetch64(x)){s_.halted=true;return false;}if(!(s_.flags&1))s_.pc=x;break;case Op::PUSH:if(!fetch8(a)||a>7||s_.sp<8||!m_.write64(s_.sp-=8,s_.r[a])){s_.halted=true;return false;}break;case Op::POP:if(!fetch8(a)||a>7||!m_.read64(s_.sp,s_.r[a])){s_.halted=true;return false;}s_.sp+=8;break;case Op::HALT:s_.halted=true;return false;default:s_.halted=true;s_.flags|=2;return false;}return true;} void CPU::run(uint64_t n){while(n--&&!s_.halted)step();}
bool Kernel::boot(){booted_=true;p_.clear();next_=1;return true;} uint32_t Kernel::spawn(const std::string&n,uint8_t pr){if(!booted_||n.empty())return 0;uint32_t id=next_++;p_.push_back({id,n,Process::State::Ready,pr});return id;} bool Kernel::kill(uint32_t id){for(auto&i:p_)if(i.pid==id&&i.state!=Process::State::Terminated){i.state=Process::State::Terminated;return true;}return false;} std::string Kernel::diagnostics()const{std::ostringstream o;o<<"LY-KERNEL: "<<(booted_?"ONLINE":"OFFLINE")<<" | processes="<<p_.size();return o.str();}
bool Lyfs::format(){f_.clear();f_["/system/boot"]="LYCAN";f_["/config/version"]="0.4.1";return true;} bool Lyfs::write(const std::string&p,const std::string&d){if(p.empty()||p[0]!='/')return false;f_[p]=d;return true;} std::optional<std::string> Lyfs::read(const std::string&p)const{auto i=f_.find(p);return i==f_.end()?std::nullopt:std::optional<std::string>(i->second);} std::vector<std::string> Lyfs::list(const std::string&p)const{std::vector<std::string>o;for(auto&i:f_)if(i.first.rfind(p,0)==0)o.push_back(i.first);std::sort(o.begin(),o.end());return o;}
bool Security::allow(const std::string&p,const std::string&cap){if(p.empty()||cap.empty())return false;a_[p]=cap;return true;} bool Security::check(const std::string&p,const std::string&cap)const{auto i=a_.find(p);return i!=a_.end()&&i->second==cap;}
Platform::Platform(size_t ram):mem_(ram),cpu_(mem_){} bool Platform::boot(){mem_.map(0,4096,true,true,true);mem_.map(4096,mem_.size()-4096,true,true,false);k_.boot();fs_.format();sec_.allow("system","boot");cpu_.reset(0,mem_.size()-16);booted_=true;return true;} std::string Platform::status()const{return booted_?k_.diagnostics()+" | LYFS=MOUNTED | SECURITY=ACTIVE":"OFFLINE";}
}
