#include "lycan_platform.h"
#include <algorithm>
#include <sstream>
namespace lycan {
Memory::Memory(size_t n):b_(n,0){} size_t Memory::size()const{return b_.size();}
bool Memory::read8(uint64_t a,uint8_t&v)const{if(a>=b_.size()||!canRead(a))return false;v=b_[a];return true;} bool Memory::write8(uint64_t a,uint8_t v){if(a>=b_.size()||!canWrite(a))return false;b_[a]=v;return true;}
bool Memory::read64(uint64_t a,uint64_t&v)const{if(a>b_.size()-8)return false;v=0;for(int i=0;i<8;i++){uint8_t x;if(!read8(a+i,x))return false;v|=(uint64_t)x<<(i*8);}return true;} bool Memory::write64(uint64_t a,uint64_t v){if(a>b_.size()-8)return false;for(int i=0;i<8;i++)if(!write8(a+i,(uint8_t)(v>>(i*8))))return false;return true;}
bool Memory::map(uint64_t a,uint64_t n,bool r,bool w,bool x){if(!n||a>b_.size()-n)return false;regions_.push_back({a,n,r,w,x});return true;} bool Memory::canRead(uint64_t a)const{for(auto i=regions_.rbegin();i!=regions_.rend();++i)if(a>=i->a&&a-i->a<i->n)return i->r;return regions_.empty();} bool Memory::canWrite(uint64_t a)const{for(auto i=regions_.rbegin();i!=regions_.rend();++i)if(a>=i->a&&a-i->a<i->n)return i->w;return regions_.empty();} bool Memory::canExecute(uint64_t a)const{for(auto i=regions_.rbegin();i!=regions_.rend();++i)if(a>=i->a&&a-i->a<i->n)return i->x;return regions_.empty();}
CPU::CPU(Memory&m):m_(m){} void CPU::reset(uint64_t e,uint64_t st){s_={};s_.pc=e;s_.sp=st;} void CPU::z(uint64_t x){if(x)s_.flags&=~1ull;else s_.flags|=1ull;} bool CPU::fetch8(uint8_t&v){if(!m_.canExecute(s_.pc)||!m_.read8(s_.pc,v))return false;s_.pc++;return true;} bool CPU::fetch64(uint64_t&v){if(!m_.canExecute(s_.pc)||s_.pc>m_.size()-8)return false;if(!m_.read64(s_.pc,v))return false;s_.pc+=8;return true;}
bool CPU::step(){if(s_.halted)return false;uint8_t o,a,b;uint64_t x;if(!fetch8(o)){s_.halted=true;return false;}switch((Op)o){case Op::NOP:break;case Op::MOV:if(!fetch8(a)||!fetch64(x)||a>7){s_.halted=true;return false;}s_.r[a]=x;z(x);break;case Op::ADD:case Op::SUB:case Op::MUL:case Op::DIV:if(!fetch8(a)||!fetch8(b)||a>7||b>7||(o==(uint8_t)Op::DIV&&!s_.r[b])){s_.halted=true;s_.flags|=2;return false;}if(o==(uint8_t)Op::ADD)s_.r[a]+=s_.r[b];else if(o==(uint8_t)Op::SUB)s_.r[a]-=s_.r[b];else if(o==(uint8_t)Op::MUL)s_.r[a]*=s_.r[b];else s_.r[a]/=s_.r[b];z(s_.r[a]);break;case Op::CMP:if(!fetch8(a)||!fetch8(b)||a>7||b>7){s_.halted=true;return false;}z(s_.r[a]-s_.r[b]);break;case Op::JMP:if(!fetch64(x)){s_.halted=true;return false;}s_.pc=x;break;case Op::JZ:if(!fetch64(x)){s_.halted=true;return false;}if(s_.flags&1)s_.pc=x;break;case Op::JNZ:if(!fetch64(x)){s_.halted=true;return false;}if(!(s_.flags&1))s_.pc=x;break;case Op::PUSH:if(!fetch8(a)||a>7||s_.sp<8||!m_.write64(s_.sp-=8,s_.r[a])){s_.halted=true;return false;}break;case Op::POP:if(!fetch8(a)||a>7||!m_.read64(s_.sp,s_.r[a])){s_.halted=true;return false;}s_.sp+=8;break;case Op::HALT:s_.halted=true;return false;default:s_.halted=true;s_.flags|=2;return false;}return true;} void CPU::run(uint64_t n){while(n--&&!s_.halted)step();}
bool Kernel::boot(){booted_=true;p_.clear();next_=1;current_=0;return true;} uint32_t Kernel::spawn(const std::string&n,uint8_t pr){if(!booted_||n.empty())return 0;uint32_t id=next_++;p_.push_back({id,n,Process::State::Ready,pr,0});return id;} bool Kernel::kill(uint32_t id){for(auto&i:p_)if(i.pid==id&&i.state!=Process::State::Terminated){i.state=Process::State::Terminated;if(current_==id)current_=0;return true;}return false;} bool Kernel::sleep(uint32_t id){for(auto&i:p_)if(i.pid==id&&i.state!=Process::State::Terminated){i.state=Process::State::Sleeping;return true;}return false;} bool Kernel::wake(uint32_t id){for(auto&i:p_)if(i.pid==id&&i.state==Process::State::Sleeping){i.state=Process::State::Ready;return true;}return false;} uint32_t Kernel::schedule(){Process*best=nullptr;for(auto&i:p_)if(i.state==Process::State::Ready&&(!best||i.priority>best->priority||(i.priority==best->priority&&i.pid<best->pid)))best=&i;for(auto&i:p_)if(i.state==Process::State::Running)i.state=Process::State::Ready;if(!best){current_=0;return 0;}best->state=Process::State::Running;best->ticks++;current_=best->pid;return current_;} std::string Kernel::diagnostics()const{size_t active=0;for(auto&i:p_)if(i.state!=Process::State::Terminated)active++;std::ostringstream o;o<<"LY-KERNEL: "<<(booted_?"ONLINE":"OFFLINE")<<" | processes="<<active<<" | current="<<current_;return o.str();}
bool Lyfs::format(){f_.clear();f_["/system/boot"]="LYCAN";f_["/config/version"]="0.6.0";return true;} bool Lyfs::write(const std::string&p,const std::string&d){if(p.empty()||p[0]!='/'||p.find("..")!=std::string::npos)return false;f_[p]=d;return true;} std::optional<std::string> Lyfs::read(const std::string&p)const{auto i=f_.find(p);return i==f_.end()?std::nullopt:std::optional<std::string>(i->second);} std::vector<std::string> Lyfs::list(const std::string&p)const{std::vector<std::string>o;for(auto&i:f_)if(i.first.rfind(p,0)==0)o.push_back(i.first);std::sort(o.begin(),o.end());return o;}
bool Security::allow(const std::string&p,const std::string&cap){if(p.empty()||cap.empty())return false;auto&v=a_[p];if(std::find(v.begin(),v.end(),cap)==v.end())v.push_back(cap);return true;} bool Security::check(const std::string&p,const std::string&cap)const{auto i=a_.find(p);return i!=a_.end()&&std::find(i->second.begin(),i->second.end(),cap)!=i->second.end();}
Syscalls::Syscalls(Kernel&k,Lyfs&f,Security&s):k_(k),fs_(f),sec_(s){} uint32_t Syscalls::spawn(const std::string&n,uint8_t p){return sec_.check("system","process.spawn")?k_.spawn(n,p):0;} bool Syscalls::terminate(uint32_t id){return sec_.check("system","process.kill")&&k_.kill(id);} std::optional<std::string> Syscalls::readFile(const std::string&caller,const std::string&p){if(!sec_.check(caller,"fs.read"))return std::nullopt;return fs_.read(p);} bool Syscalls::writeFile(const std::string&caller,const std::string&p,const std::string&d){return sec_.check(caller,"fs.write")&&fs_.write(p,d);}
Platform::Platform(size_t ram):mem_(ram),cpu_(mem_),sc_(k_,fs_,sec_){} bool Platform::boot(){if(mem_.size()<8192)return false;mem_.map(0,4096,true,true,true);mem_.map(4096,mem_.size()-4096,true,true,false);k_.boot();fs_.format();sec_.allow("system","boot");sec_.allow("system","process.spawn");sec_.allow("system","process.kill");sec_.allow("system","fs.read");sec_.allow("system","fs.write");cpu_.reset(0,mem_.size()-16);booted_=true;return true;} std::string Platform::status()const{return booted_?k_.diagnostics()+" | LYFS=MOUNTED | SECURITY=ACTIVE":"OFFLINE";}
Snapshot Platform::snapshot()const{Snapshot s;s.cpu=cpu_.state();for(auto&p:fs_.list("/")){auto d=fs_.read(p);if(d)s.files.push_back({p,*d});}return s;} bool Platform::restore(const Snapshot&s){if(!booted_)return false;cpu_.setState(s.cpu);if(!fs_.format())return false;for(auto&p:s.files)if(!fs_.write(p.first,p.second))return false;return true;}
}
