#include "win32_desktop.h"
#define NOMINMAX
#include <windows.h>
#include <algorithm>
#include <string>
namespace lycan {
static AppHost* gHost=nullptr; static int gPage=0;
static std::wstring wide(const std::string&s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring w(n,L' ');MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),w.data(),n);return w;}
static void drawText(HDC dc,const std::wstring&s,int x,int y,int size=15,bool bold=false){HFONT f=CreateFontW(size,0,0,0,bold?FW_SEMIBOLD:FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH|FF_DONTCARE,L"Segoe UI");auto old=SelectObject(dc,f);SetTextColor(dc,RGB(229,233,240));SetBkMode(dc,TRANSPARENT);TextOutW(dc,x,y,s.c_str(),(int)s.size());SelectObject(dc,old);DeleteObject(f);}
static void panel(HDC dc,RECT r,COLORREF c){HBRUSH b=CreateSolidBrush(c);HRGN rg=CreateRoundRectRgn(r.left,r.top,r.right,r.bottom,16,16);FillRgn(dc,rg,b);DeleteObject(rg);DeleteObject(b);}
static void nav(HDC dc,int y,const wchar_t*t,bool active){panel(dc,{34,y,232,y+44},active?RGB(42,51,67):RGB(24,29,37));drawText(dc,t,52,y+12,14,active);}
static void paint(HWND hwnd,HDC dc){RECT r;GetClientRect(hwnd,&r);HBRUSH bg=CreateSolidBrush(RGB(10,13,18));FillRect(dc,&r,bg);DeleteObject(bg);panel(dc,{18,18,246,r.bottom-18},RGB(18,22,29));drawText(dc,L"LYCAN",42,38,26,true);drawText(dc,L"VIRTUAL ENVIRONMENT",42,69,9);
 const wchar_t* items[]={L"⌂   Desktop",L"▦   Store",L"▣   Files",L">_  Terminal",L"◉   Web",L"⚙   Settings",L"◌   Diagnostics"};for(int i=0;i<7;i++)nav(dc,104+i*50,items[i],gPage==i);drawText(dc,L"LYCAN 1.0",46,r.bottom-55,11);drawText(dc,L"Windows host · isolated",46,r.bottom-35,10);
 int x=270;std::wstring title=items[gPage];if(gPage==0)title=L"Good afternoon.";drawText(dc,title,x,38,31,true);drawText(dc,L"A virtual operating environment running above Windows.",x,76,13);
 if(gPage==0){panel(dc,{x,110,r.right-24,225},RGB(19,24,32));drawText(dc,L"SYSTEM STATUS",x+22,130,11,true);drawText(dc,wide("ARES CPU  •  "+gHost->vm().cpu().state()),x+22,158,14);drawText(dc,L"Virtual RAM     256 KiB guest allocation",x+22,184,13);drawText(dc,wide("LYFS  •  "+std::to_string(gHost->fs().usedBytes()/1024)+" KiB used of 4 GiB").c_str(),x+22,208,13);
 panel(dc,{x,245,(r.right+x)/2,390},RGB(19,24,32));panel(dc,{(r.right+x)/2+14,245,r.right-24,390},RGB(19,24,32));drawText(dc,L"BOOT PIPELINE",x+22,266,11,true);drawText(dc,wide(gHost->vm().bootStage()),x+22,301,26,true);drawText(dc,L"Firmware  →  MMU  →  Kernel  →  Services  →  Desktop",x+22,345,11);drawText(dc,L"GUEST PROCESSES",(r.right+x)/2+34,266,11,true);auto ps=gHost->processes().list();int yy=300;for(const auto&p:ps){drawText(dc,wide(std::to_string(p.pid)+"   "+p.name+"   "+p.state), (r.right+x)/2+34,yy,12);yy+=24;}
 panel(dc,{x,410,r.right-24,r.bottom-28},RGB(19,24,32));drawText(dc,L"RECENT EVENTS",x+22,432,11,true);yy=462;for(const auto&l:gHost->vm().log()){drawText(dc,wide(l),x+22,yy,11);yy+=19;if(yy>r.bottom-44)break;}}
 else {panel(dc,{x,110,r.right-24,r.bottom-28},RGB(19,24,32));drawText(dc,gPage==1?L"LYCAN STORE":gPage==2?L"LYFS FILES":gPage==3?L"LYCAN TERMINAL":gPage==4?L"LYCAN WEB":gPage==5?L"SETTINGS":L"DIAGNOSTICS",x+22,135,22,true);if(gPage==1){drawText(dc,L"Free applications",x+22,173,12);drawText(dc,L"LYCAN Terminal",x+22,218,16,true);drawText(dc,L"Signed LYCAN utility",x+22,244,12);drawText(dc,L"INSTALL",x+22,276,12,true);drawText(dc,L"LYCAN Files",x+270,218,16,true);drawText(dc,L"Guest filesystem manager",x+270,244,12);drawText(dc,L"INSTALL",x+270,276,12,true);drawText(dc,L"LYCAN Web",x+520,218,16,true);drawText(dc,L"Real Gecko integration surface",x+520,244,12);drawText(dc,L"OPEN",x+520,276,12,true);}else if(gPage==2){int y=178;for(auto&e:gHost->fs().list("/")){drawText(dc,wide((e.directory?"▰ ":"▱ ")+e.path),x+28,y,13);y+=30;}}else if(gPage==3){drawText(dc,L"Guest shell",x+22,176,13);drawText(dc,L"help   ls   cat /home/Welcome.txt   ps   vm",x+22,210,12);drawText(dc,L"Use lycan-cli for full interactive terminal I/O.",x+22,240,12);}else if(gPage==4){drawText(dc,L"MOZILLA GECKO",x+22,178,16,true);drawText(dc,L"This surface accepts only a genuine Gecko runtime.",x+22,210,13);drawText(dc,L"The build does not substitute Chromium or an iframe.",x+22,236,13);}else if(gPage==5){drawText(dc,L"Appearance",x+22,178,16,true);drawText(dc,L"Dark desktop · glass panels · motion-ready shell",x+22,208,13);drawText(dc,L"Storage",x+22,250,16,true);drawText(dc,L"Private guest filesystem backed by LycanOS data.",x+22,280,13);}else{drawText(dc,wide(gHost->security().describe()),x+22,178,13);drawText(dc,wide("VM cycles: "+std::to_string(gHost->vm().cpu().cycles())),x+22,210,13);drawText(dc,L"Snapshots enabled",x+22,242,13);}}
 }
static LRESULT CALLBACK wnd(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_PAINT){PAINTSTRUCT p;HDC d=BeginPaint(h,&p);paint(h,d);EndPaint(h,&p);return 0;}if(m==WM_LBUTTONUP&&LOWORD(l)<250&&HIWORD(l)>=104&&HIWORD(l)<454){gPage=std::clamp((HIWORD(l)-104)/50,0,6);InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
int runDesktop(AppHost&host){gHost=&host;WNDCLASSW wc{};wc.lpfnWndProc=wnd;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"LYCAN.Desktop";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);RegisterClassW(&wc);HWND h=CreateWindowExW(0,wc.lpszClassName,L"LYCAN OS",WS_OVERLAPPEDWINDOW|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,1280,820,nullptr,nullptr,wc.hInstance,nullptr);MSG msg;while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return(int)msg.wParam;}
}
