#include "network.h"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>
namespace lycan {
namespace { std::string trim(const std::string&s){auto a=s.find_first_not_of(" \t\r\n");if(a==std::string::npos)return{};auto b=s.find_last_not_of(" \t\r\n");return s.substr(a,b-a+1);} }
NetworkStack::NetworkStack(std::filesystem::path root):root_(std::move(root)){}
void NetworkStack::boot(){std::filesystem::create_directories(root_);load();if(interfaces_.empty()){interfaces_.push_back({"VNET0","UP","10.42.0.2","10.42.0.1","10.42.0.1"});interfaces_.push_back({"LOOP0","UP","127.0.0.1","",""});internet_=true;persist();}}
bool NetworkStack::online()const noexcept{const auto*v=find("VNET0");return internet_&&v&&v->state=="UP";}
bool NetworkStack::validName(const std::string&n)const{if(n.empty()||n.size()>16)return false;for(char c:n)if(!(std::isalnum(static_cast<unsigned char>(c))||c=='_'))return false;return true;}
bool NetworkStack::validIpv4(const std::string&ip)const{std::stringstream ss(ip);std::string p;int count=0;while(std::getline(ss,p,'.')){if(p.empty()||p.size()>3||++count>4||!std::all_of(p.begin(),p.end(),[](char c){return std::isdigit(static_cast<unsigned char>(c));}))return false;try{auto n=std::stoi(p);if(n<0||n>255)return false;}catch(...){return false;}}return count==4;}
NetworkInterface* NetworkStack::find(const std::string&n){auto it=std::find_if(interfaces_.begin(),interfaces_.end(),[&](const auto&i){return i.name==n;});return it==interfaces_.end()?nullptr:&*it;}
const NetworkInterface* NetworkStack::find(const std::string&n)const{auto it=std::find_if(interfaces_.begin(),interfaces_.end(),[&](const auto&i){return i.name==n;});return it==interfaces_.end()?nullptr:&*it;}
void NetworkStack::persist()const{std::ofstream f(root_/"network.state",std::ios::trunc);if(!f)return;f<<"LYCAN-VNET 1\ninternet="<<(internet_?"on":"off")<<"\n";for(const auto&i:interfaces_)f<<"if="<<i.name<<','<<i.state<<','<<i.address<<','<<i.gateway<<','<<i.dns<<"\n";}
void NetworkStack::load(){interfaces_.clear();internet_=true;std::ifstream f(root_/"network.state");if(!f)return;std::string l,h;std::getline(f,h);if(h!="LYCAN-VNET 1")return;while(std::getline(f,l)){auto eq=l.find('=');if(eq==std::string::npos)continue;auto k=l.substr(0,eq),v=l.substr(eq+1);if(k=="internet")internet_=v=="on";else if(k=="if"){std::stringstream ss(v);std::string a,b,c,d,e;if(std::getline(ss,a,',')&&std::getline(ss,b,',')&&std::getline(ss,c,',')&&std::getline(ss,d,',')&&std::getline(ss,e,','))if(validName(a)&&(b=="UP"||b=="DOWN")&&validIpv4(c)&&(d.empty()||validIpv4(d))&&(e.empty()||validIpv4(e)))interfaces_.push_back({a,b,c,d,e});}}}
std::string NetworkStack::list()const{std::string o="INTERFACE  STATE  ADDRESS       GATEWAY      DNS          TYPE\n";for(const auto&i:interfaces_)o+=i.name+"        "+i.state+"    "+i.address+"    "+(i.gateway.empty()?"-":i.gateway)+"      "+(i.dns.empty()?"-":i.dns)+"       "+(i.name=="LOOP0"?"LOOPBACK":"VIRTUAL")+"\n";return o;}
std::string NetworkStack::routes()const{const auto*v=find("VNET0");if(!v||v->state!="UP")return "ROUTING TABLE\n(no active VNET route)";return "ROUTING TABLE\nDESTINATION      GATEWAY        DEVICE\n0.0.0.0/0        "+v->gateway+"     VNET0\n10.42.0.0/24     DIRECT         VNET0\n127.0.0.0/8      LOCAL          LOOP0";}
std::string NetworkStack::dns()const{const auto*v=find("VNET0");return std::string("DNS CONFIGURATION\nVNET0: ")+(v&&!v->dns.empty()?v->dns:"UNSET")+"\nRESOLUTION: "+(online()?"ENABLED":"DISABLED");}
std::string NetworkStack::setInterfaceState(const std::string&n,bool up){auto*i=find(n);if(!i)return "INTERFACE NOT FOUND";if(n=="LOOP0"&&!up)return "REFUSED: LOOPBACK IS MANDATORY";i->state=up?"UP":"DOWN";persist();return "INTERFACE "+n+" "+i->state;}
std::string NetworkStack::configure(const std::string&s){std::stringstream ss(s);std::string n,a,g,d;if(!(ss>>n>>a>>g>>d))return "USAGE: vnet config <name> <address> <gateway> <dns>";auto*i=find(n);if(!i)return "INTERFACE NOT FOUND";if(!validIpv4(a)||(g!="-"&&!validIpv4(g))||(d!="-"&&!validIpv4(d)))return "INVALID IPV4 CONFIGURATION";i->address=a;i->gateway=g=="-"?"":g;i->dns=d=="-"?"":d;persist();return "INTERFACE CONFIGURED "+n;}
std::string NetworkStack::execute(const std::string&command){auto c=trim(command);if(c=="vnet"||c=="vnet status")return std::string("VIRTUAL NETWORK ")+(online()?"ONLINE":"OFFLINE")+"\nINTERNET "+(internet_?"ALLOWED":"BLOCKED")+"\n"+list();if(c=="vnet interfaces")return list();if(c=="vnet routes")return routes();if(c=="vnet dns")return dns();if(c=="vnet on"){internet_=true;if(auto*i=find("VNET0"))i->state="UP";persist();return "VNET ONLINE";}if(c=="vnet off"){internet_=false;if(auto*i=find("VNET0"))i->state="DOWN";persist();return "VNET OFFLINE";}if(c.rfind("vnet up ",0)==0)return setInterfaceState(trim(c.substr(8)),true);if(c.rfind("vnet down ",0)==0)return setInterfaceState(trim(c.substr(10)),false);if(c.rfind("vnet config ",0)==0)return configure(c.substr(12));return "VNET COMMAND NOT FOUND. Try: vnet status | vnet interfaces | vnet routes | vnet dns | vnet on | vnet off | vnet up <if> | vnet down <if> | vnet config <if> <ip> <gateway> <dns>";}
}